{% set name = "types-orjson" %}
{% set version = "3.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-orjson-{{ version }}.tar.gz
  sha256: e8513f75886a13e6061f5658d53d57d97b3af20cb9c3dcee09e31793f3cee28f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/orjson-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for orjson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
